const URLs = {
  "/": "Home",
  "/signin": "Sign In",
  "/signup": "Sign Up",
  "/resetpassword": "Reset Password",
  "/sendotp": "Send OTP",
  "/verify": "Verify OTP",
  "/location/vehicle-route": "Vehicle Route",
  "/location/current-location": "Current Location",
  "/dashboard": "Dashboard",
  "/reports/engine": "Engine Report",
  "/reports/location": "Location Report",
  "/reports/speed": "Speed Report",
  "/reports/distance-report/hourly": "Hourly Distance Report",
  "/reports/distance-report/daily": "Daily Distance Report",
  "/reports/distance-report/monthly": "Monthly Distance Report",
  "/activity/location-share-list": "Location Share List",
  "/activity/route-share-list": "Route Share List",
  "/activity/alerts/overspeed": "Overspeed Alert",
  "/activity/alerts/panic": "Panic Alert",
  "/activity/alerts/driving-fatigue": "Driving Fatigue Alert",
  "/activity/alerts/offline": "Offline Alert",
  "/activity/alerts/disconnection": "Disconnection Alert",
  "/activity/alerts/summary": "Alert Summary",
  "/activity/alerts/manage": "Manage Alerts",
  "/activity/geo-fence": "Geo Fence",
  "/activity/geo-fence/create": "Create Geo Fence",
  "/activity/geo-fence/update": "Update Geo Fence",
  "/activity/geo-fence/event": "Geo Fence Event",
  "/activity/geo-fence/assign": "Assign Geo Fence",
  "/support/vehicle-profile": "Vehicle Profile",
  "/support/edit-vehicle-profile": "Edit Vehicle Profile",
  "/support/device-details": "Device Details",
  "/support/vehicle-group": "Vehicle Group",
  "/support/vehicle-group/id": "Vehicle Group Details",
  "/support/messages": "Messages",
  "/support/ticket": "Create Support Ticket",
  "/billing/transaction-history": "Transaction History",
  "/billing/due-invoice": "Due Invoice",
  "/billing/paid-invoice": "Paid Invoice",
  "/billing/make-payment": "Make Payment",
  "/user-profile": "User Profile",
  "/analytics-and-summary": "Analytics and Summary",
  "/notifications": "Notifications",
  "/impersonate": "Impersonate",
  "/switchUser": "Switch User",
  "/loginLink": "Login New User",
  "/subadmin": "Subadmin",
  "/subadmin/create": "Create Subadmin",
};

const findUrlName = (url) => {
  return URLs[url];
};

export default findUrlName;
